codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
        target: 70%
        threshold: 1%
    patch:
      default:
        target: 60%

comment:
  layout: "reach, diff, flags, files"
  behavior: default
